Shellcheck

diff --git a/bin/mani-tag b/bin/mani-tag
--- a/bin/mani-tag
+++ b/bin/mani-tag
@@ -12,22 +12,8 @@ function help()
     echo "  -d tag1,tag2,...            Delete tags from projects"
     echo "  -c                          Clear all tags for projects"
     echo "  -h                          Show this help message"
-    exit
+    exit "${1:-0}"
 }
-
-[[ "$#" -eq 0 ]] && help
-
-# Check for required executables.
-if ! command -v flock &>/dev/null
-then
-    echo "Required executable not found: flock"
-    exit 1
-fi
-if ! command -v yq &>/dev/null
-then
-    echo "Required executable not found: yq"
-    exit 1
-fi
 
 # Variables to be used in the script.
 root=       # The 'mani' root containing the 'mani.yaml' file.
@@ -38,8 +24,23 @@ selector=   # Multiple path selector for yq
 add=        # Tags to add.
 delete=     # Tags to delete.
 clr=        # Clear all tags flag.
-helpmsg=    # Show help message
 all=        # Flag to select all projects.
+
+# Parse arguments
+[[ "$#" -eq 0 ]] && help 1
+
+while getopts "p:Pa:d:ch" flag
+do
+    case "$flag" in
+        "p") IFS=',' read -ra projects <<< "$OPTARG";;
+        "P") all=1;;
+        "a") add="[\"${OPTARG//,/\",\"}\"]";;
+        "d") delete="[\"${OPTARG//,/\",\"}\"]";;
+        "c") clr=1;;
+        "h") help 0;;
+        *) help 1;;
+    esac
+done
 
 # Find 'mani' root.
 pushd . &>/dev/null
@@ -53,7 +54,7 @@ do
     cd ..
 done
 root="$PWD"
-popd &>/dev/null
+popd &>/dev/null || exit 1
 
 # Set config file.
 config="$root/mani.yaml"
@@ -61,18 +62,17 @@ config="$root/mani.yaml"
 # Set relative path compare to 'mani' root.
 [[ "$root" != "$PWD" ]] && relative=${PWD//$root\//}
 
-# Parse arguments
-while getopts "p:Pa:d:ch" flag
-do
-    case "$flag" in
-        "p") IFS=',' read -a projects <<< "$OPTARG";;
-        "P") all=1;;
-        "a") add="[\"${OPTARG//,/\",\"}\"]";;
-        "d") delete="[\"${OPTARG//,/\",\"}\"]";;
-        "c") clr=1;;
-        "h") help;;
-    esac
-done
+# Check for required executables.
+if ! command -v flock &>/dev/null
+then
+    echo "Required executable not found: flock"
+    exit 1
+fi
+if ! command -v yq &>/dev/null
+then
+    echo "Required executable not found: yq"
+    exit 1
+fi
 
 if [[ -n "$all" ]]
 then
@@ -81,7 +81,7 @@ else
     # Find project based on 'mani.yaml' and relative path.
     if [[ "${#projects[@]}" -eq 0 ]]
     then
-        projects=( $(yq -r ".projects | to_entries | .[] | select(.value.path == \"$relative\") | .key" "$config") )
+        projects=( "$(yq -r ".projects | to_entries | .[] | select(.value.path == \"$relative\") | .key" "$config")" )
         if [[ ${#projects[@]} -eq 0 ]]
         then
             findname="$(yq ".projects | has(\"$relative\")" "$config")"
@@ -98,8 +98,8 @@ else
     selector="("
     for project in "${projects[@]}"
     do
-        [[ "$(yq .projects.$project $config)" == "null" ]] && echo "No project with name '$project' in '$config'." && exit 1
-        selector+=".projects.$project.tags, "
+        [[ "$(yq ".projects.\"$project\"" "$config")" == "null" ]] && echo "No project with name '$project' in '$config'." && exit 1
+        selector+=".projects.\"$project\".tags, "
     done
     selector="${selector:0:-2})"
 fi
@@ -108,15 +108,15 @@ fi
 # Handle arguments
 if [[ -n "$delete" ]]
 then
-    flock $config command yq -i "$selector |= (filter([.] - $delete | length > 0) | sort)" $config
+    flock "$config" command yq -i "$selector |= (filter([.] - $delete | length > 0) | sort)" "$config"
 fi
 
 if [[ -n "$add" ]]
 then
-    flock $config command yq -i "$selector |= (. + $add | unique | sort)" $config
+    flock "$config" command yq -i "$selector |= (. + $add | unique | sort)" "$config"
 fi
 
 if [[ -n "$clr" ]]
 then
-    flock $config command yq -i "$selector = []" $config
+    flock "$config" command yq -i "$selector = []" "$config"
 fi
